version: '3.8'

services:
  app:
    build:
      context: .
      args:
        PORT: 3131
    ports:
      - '3131:3131'
    environment:
      - PORT=3131
    env_file:
      - ./.env
    depends_on:
      - db
      # - redis
    volumes:
      - ./static:/app/static
    command: npm start

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  # redis:
  #   image: redis:7
  #   restart: always

volumes:
  pgdata:
